repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace  # убирает лишние пробелы
    -   id: check-added-large-files  # проверяет тяжелые файлы на изменения
    -   id: end-of-file-fixer  # добавляет пустую строку в конце файла
    -   id: check-yaml  # проверяет синтаксис .yaml файлов
    -   id: check-json  # проверяет синтаксис .json файлов
    -   id: check-case-conflict  # проверяет файлы, которые могут конфликтовать в файловых системах без учета регистра.
    -   id: check-merge-conflict  # проверяет файлы, содержащие конфликтные строки слияния.
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1 # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
        args: ["--profile", "black"]

# Сканер стилистических ошибок, нарушающие договоренности PEP8
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        exclude: __init__.py
        args: [ "--ignore=F821", "--max-line-length=120", "--ignore=W503" ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    
-   repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
    -   id: black
